### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by JagaRamesh** [milesin3d/intro-data-capstone-musclehub#1]
Excellent job with the coding and the powerpoint presentation!

The powerpoint slides are exceptional, sequenced very well and communicated the information visually.

The matplotlib plots are neat with proper title, xlabel and ylabel defined. It's great to see that you explored the commands like "ax.text" for showing the value on the barplot. 

The hypothesis test results are correct and the final recommendation is accurate. The "recommended future studies" are very good and well thought out.

Awesome work! KEEP IT UP!!

**Comment by milesin3d** [comment]
I appreciate you reviewing my work and reaching out after the course. I really enjoyed learning in this class. It was a great learning experience and I look to further my development in this area. To further my development, I am taking a "Data Science Career Track" with Springboard.
